---
- name: Master node
  hosts: cks-master
  become: true
  roles:
    - role: base
      vars:
        falco:
          enabled: false
        kube_bench:
          enabled: true
    - role: master
