---
- name: Worker nodes
  hosts: cks-worker
  become: true
  roles:
    - role: base
      vars:
        falco:
          enabled: true
        kube_bench:
          enabled: false
    - role: worker
