- name: Worker | check kubelet conf file
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: worker_join
  tags: join

- name: Worker | wait for master
  ansible.builtin.wait_for:
    host: cks-master
    port: 6443
  delegate_to: cks-master
  when: not worker_join.stat.exists
  tags: join

- name: Worker | register join command on master
  ansible.builtin.command: |
    kubeadm token create --print-join-command --ttl 0
  delegate_to: cks-master
  register: join_command
  when: not worker_join.stat.exists
  changed_when: false
  tags: join

- name: Worker | join cluster
  ansible.builtin.command: "{{ join_command.stdout }}"
  when: not worker_join.stat.exists
  changed_when: not worker_join.stat.exists
  tags: join
