# https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/#deploy-cilium
- name: "Cilium | helm repository"
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  tags: cni, cilium

# TODO: idempotency
- name: "Cilium | helm installation"
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values:
      bpf:
        masquerade: true
      cni:
        exclusive: false # prevent shoot podman cni conf
      k8sServiceHost: "{{ ansible_default_ipv4.address }}"
      k8sServicePort: 6443 # the default port
      kubeProxyReplacement: true
  tags: cni, cilium

- name: "Cilium | Cilium CLI"
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium.cli.version }}/cilium-linux-amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
  tags: cilium
