# https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/#deploy-cilium
- name: "Cilium | helm repository"
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  tags: cni, cilium

- name: "Cilium | helm installation"
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
  tags: cni, cilium
