# https://open-policy-agent.github.io/gatekeeper/website/docs/install/#deploying-via-helm
- name: "OPA | helm repository"
  kubernetes.core.helm_repository:
    name: gatekeeper
    repo_url: https://open-policy-agent.github.io/gatekeeper/charts
  tags: opa

- name: "OPA | installation by helm"
  kubernetes.core.helm:
    name: gatekeeper
    chart_ref: gatekeeper/gatekeeper
    release_namespace: gatekeeper-system
    create_namespace: true
  tags: opa

- name: "OPA | install opa constrainttemplate"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'opa_repo_constrainttemplate.yaml') | from_yaml }}"
  register: constrainttemplate

- name: "OPA | wait 10s before install constraint"
  ansible.builtin.wait_for:
    timeout: 10
  when: constrainttemplate is changed

- name: "OPA | install opa constraint"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'opa_repo_constraint.yaml') | from_yaml }}"
  register: constrainttemplate

