- name: "Setup ansible | apt packages"
  ansible.builtin.apt:
    name:
      - python3-pip
    update_cache: true
  tags: packages, apt

## For idempotency
- name: "Setup ansible | check if python3-kubernetes is installed"
  ansible.builtin.command: |
    pip3 list --format columns | grep kubernetes
  changed_when: false
  ignore_errors: true
  register: python_kubernetes_installed
  tags: packages, pip

- name: "Setup ansible | pip packages"
  # python3-kubernetes v7.0.0 in ubuntu 20.04 outdated use pip instead
  ansible.builtin.pip:
    name: kubernetes
    extra_args: "--user"
  when: python_kubernetes_installed.rc != 0
  tags: packages, pip

# For idempotency, check a file to see if kubeadm already init
- name: "Kubernetes | check if needed"
  ansible.builtin.stat:
    path: /etc/kubernetes/scheduler.conf
  register: kubeadm_file
  tags: kubeadm

- name: "Kubernetes | kubeadm init"
  ansible.builtin.command:
    kubeadm init \
    --kubernetes-version={{ kubernetes.version }} \
    --ignore-preflight-errors=NumCPU \
    --skip-token-print \
    --pod-network-cidr 192.168.0.0/16
    --skip-phases=addon/kube-proxy
  when: not kubeadm_file.stat.exists
  changed_when: not kubeadm_file.stat.exists
  tags: kubeadm

- name: "Kubernetes | user .kube directory"
  ansible.builtin.file:
    path: ~/.kube
    mode: "0755"
    state: directory
  tags: kubeadm

- name: "Kubernetes | copy kubeconfig"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    mode: "0600"
    remote_src: true
  tags: kubeadm

- name: "Helm | install"
  ansible.builtin.include_tasks:
    file: helm.yml
  tags: helm

- name: "Cilium CNI | install"
  ansible.builtin.include_tasks:
    file: cilium_cni.yml
  tags: cilium, cni

- name: "Etcdctl"
  ansible.builtin.unarchive:
    src: "https://github.com/etcd-io/etcd/releases/download/{{ etcdctl.version }}/etcd-{{ etcdctl.version }}-linux-amd64.tar.gz"
    dest: /usr/bin/
    remote_src: true
    extra_opts:
      - --strip-components=1
      - etcd-{{ etcdctl.version }}-linux-amd64/etcdctl
  tags: etcd

- name: "Metrics Server | install"
  ansible.builtin.include_tasks:
    file: metrics_server.yml
  tags: metrics

# - name: "OPA/Gatekeeper | install"
#   ansible.builtin.include_tasks:
#     file: gatekeeper.yml
