- name: "setup ansible | apt packages"
  apt:
    name:
    - python3-pip
    update_cache: yes
  tags: packages, apt

## For idempotency
- name: "setup ansible | check if python3-kubernetes is installed"
  shell: |
    pip3 list --format columns | grep kubernetes
  changed_when: false
  ignore_errors: yes
  register: python_kubernetes_installed
  tags: packages, pip

- name: "setup ansible | pip packages"
  # python3-kubernetes v7.0.0 in ubuntu 20.04 outdated use pip instead
  pip:
    name: kubernetes
    extra_args: "--user"
  when: python_kubernetes_installed.rc != 0
  tags: packages, pip

# For idempotency, check a file to see if kubeadm already init
- name: "init k8s | check if needed"
  stat:
    path: /etc/kubernetes/scheduler.conf
  register: kubeadm_file
  tags: kubeadm

- name: "init k8s | kubeadm init"
  shell:
    kubeadm init \
    --kubernetes-version={{ KUBERNETES_VERSION }} \
    --ignore-preflight-errors=NumCPU \
    --skip-token-print \
    --pod-network-cidr 192.168.0.0/16
  when: not kubeadm_file.stat.exists
  tags: kubeadm

- name: "init k8s | user .kube directory"
  file:
    path: ~/.kube
    state: directory
  tags: kubeadm

- name: "init k8s | copy kubeconfig"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    mode: "0600"
    remote_src: yes
  tags: kubeadm

- name: "Helm | install"
  ansible.builtin.include_tasks:
    file: helm.yml
  tags: helm

- name: "Cilium CNI | install"
  ansible.builtin.include_tasks:
    file: cilium_cni.yml
  tags: cilium, cni

- name: "etcdctl"
  unarchive:
    src: "https://github.com/etcd-io/etcd/releases/download/{{ ETCDCTL_VERSION }}/etcd-{{ ETCDCTL_VERSION }}-linux-amd64.tar.gz"
    dest: /usr/bin/
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - etcd-{{ ETCDCTL_VERSION }}-linux-amd64/etcdctl
  tags: etcd

#- name: "OPA/Gatekeeper | install"
#  ansible.builtin.include_tasks:
#    file: gatekeeper.yml
