# See https://docs.linuxfoundation.org/tc-docs/certification/important-instructions-cks#cks-environment
- name: "Ensure additionnal tools | apt"
  ansible.builtin.apt:
    name:
      - jq
      - tmux
      - curl
      - wget

- name: "Additionnal tools | snap"
  community.general.snap:
    name: yq
