# Didn't figure out why Kim done that…
# - name: "Containerd | containerd 1.6 over apt-installed-version"
#   unarchive:
#     src: " https://github.com/containerd/containerd/releases/download/v{{ CONTAINERD_VERSION }}/containerd-{{ CONTAINERD_VERSION }}-linux-amd64.tar.gz"
#     dest: /usr/bin/
#     remote_src: true
#     extra_opts:
#     - --strip-components=1
#   notify: Restart containerd
#   tags: containerd

- name: "Containerd | kernel modules conf"
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/containerd.conf
    mode: "0644"
    line: "{{ item }}"
    create: true
    state: present
  with_items:
    - overlay
    - br_netfilter
  notify: Restart containerd
  tags: containerd

- name: "Containerd | kernel modules load"
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter
  notify: Restart containerd
  tags: containerd

- name: "Containerd | sysctl configuration"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
  notify: Restart containerd
  tags: containerd

- name: "Containerd | containerd configuration path"
  ansible.builtin.file:
    path: /etc/containerd
    mode: "0755"
    state: directory
  notify: Restart containerd
  tags: containerd

- name: "Containerd configuration | containerd config"
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "0644"
  notify: Restart containerd
  tags: containerd

- name: "Containerd configuration | crictl containerd runtime"
  ansible.builtin.lineinfile:
    path: /etc/crictl.yaml
    mode: "0644"
    create: true
    line: "runtime-endpoint: unix:///run/containerd/containerd.sock"
    state: present
  notify: Restart containerd
  tags: containerd, crictl

- name: "Containerd configuration | kubelet containerd runtime"
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    mode: "0644"
    create: true
    line: KUBELET_EXTRA_ARGS="--container-runtime-endpoint unix:///run/containerd/containerd.sock"
    state: present
  notify: Restart containerd
  tags: containerd, kubelet

# https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-2-from-apt-get-or-dnf
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
- name: "Containerd | docker repo key"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  register: docker_repo_key
  tags: packages, apt, containerd

- name: "Containerd | docker repo"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_repo_key.dest }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: true
    state: present
  tags: packages, apt, containerd

- name: "Containerd | containerd.io package"
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: true
  tags: packages, apt, containerd
