# https://gvisor.dev/docs/user_guide/install/
#
- name: "GVisor | gvisor apt repo key"
  ansible.builtin.apt_key:
    url: https://gvisor.dev/archive.key
    state: present
  tags: packages, apt, gvisor

- name: "GVisor | gvisor apt repo"
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://storage.googleapis.com/gvisor/releases release main
    filename: gvisor
    update_cache: true
    state: present
  tags: packages, apt, gvisor

- name: "GVisor | runsc package"
  ansible.builtin.apt:
    name: runsc
    state: present
    update_cache: true
  tags: packages, apt, gvisor
