- name: "setup terminal | packages"
  apt:
    name:
    - bash-completion
    - binutils
    update_cache: yes
  tags: packages, apt

- name: "setup terminal | vim configuration"
  blockinfile:
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    path: ~/.vimrc
    create: yes
    block: |
      colorscheme ron
      set tabstop=2
      set shiftwidth=2
      set expandtab
      set autoindent

- name: "setup terminal | bash configuration"
  blockinfile:
    path: ~/.bashrc
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      alias c=clear
      complete -F __start_kubectl k
  tags: bash

- name: "setup terminal | bash configuration"
  replace:
    path: ~/.bashrc
    regexp: '^#(force_color_prompt=yes)$'
    replace: '\1'
  tags: bash

- name: "tools | include exam additionnal tools"
  ansible.builtin.include_tasks:
    file: additionnal_tools.yml

- name: "disable swap | disable swap"
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0
  tags: swap

- name: "disable swap | comment swap partition in fstab"
  ansible.posix.mount:
    path: none
    fstype: swap
    state: absent
  tags: swap

- name: "apt | keyrings directory"
  file:
    path: /etc/apt/keyrings
    state: directory
  tags: packages, apt

- name: "podman | install and configure podman"
  ansible.builtin.include_tasks:
    file: podman.yml

# TODO: This on ansible 2.15
#- name: "packages | kubernetes repo"
#  ansible.builtin.deb822_repository:
#    name: kubernetes
#    types: [deb]
#    uris: "https://apt.kubernetes.io"
#    signed_by: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
#    suites: [kubernetes-xenial]
#    components: [main]
#    state: present
#    enabled: yes
#  tags: packages, apt

- name: "packages | kubernetes repo key"
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
  register: kubernetes_repo_key
  tags: packages, apt

- name: "packages | kubernetes repo"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ kubernetes_repo_key.dest }}] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
    update_cache: yes
    state: present
  tags: packages, apt

- name: "packages | kubernetes packages"
  apt:
    name:
    - "kubelet={{ KUBERNETES_VERSION }}-00"
    - "kubeadm={{ KUBERNETES_VERSION }}-00"
    - "kubectl={{ KUBERNETES_VERSION }}-00"
    - kubernetes-cni
    state: present
    update_cache: yes
  tags: packages, apt

- name: "packages | hold kubernetes packages"
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
  - kubelet
  - kubectl
  - kubeadm
  - kubernetes-cni
  tags: packages, apt

- name: "gvisor | install and configure gvisor"
  ansible.builtin.include_tasks:
    file: gvisor.yml
  when: gvisor.enabled

- name: "containerd | install and configure containerd"
  ansible.builtin.include_tasks:
    file: containerd.yml

- name: "kubelet | kube-bench 4.1.1 kubelet service file permissions"
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    state: file
    owner: root
    group: root
    mode: "0600"
  tags: kubelet

  # TODO: use handlers ?
- name: "services | kubelet enabled and started"
  ansible.builtin.systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: yes
  tags: kubelet

- name: "course | git clone cks course repository"
  ansible.builtin.git:
    repo: https://github.com/killer-sh/cks-course-environment.git
    dest: /root/cks-course-environment

- name: "falco | install and run falco"
  ansible.builtin.include_tasks:
    file: falco.yml
  when: falco.enabled

- name: "kube-bench | install kube-bench"
  ansible.builtin.include_tasks:
    file: kube-bench.yml
  when: kube_bench.enabled
